apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-graceful
spec:
  selector:
    matchLabels:
      app: example-graceful
  replicas: 1
  template:
    metadata:
      labels:
        app: example-graceful
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: beck33/example-graceful:0.15
          imagePullPolicy: Always
          name: example-graceful
          ports:
            - containerPort: 8080
          # command: ["/bin/sh", "-c", "sleep 1000"]
          lifecycle:
            preStop:
              httpGet:
                port: 8080
                path: /unhealthy
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 1
          readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/readiness
              initialDelaySeconds: 10
              periodSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: example-graceful
spec:
  type: LoadBalancer
  selector:
    app: example-graceful
  ports:
  - port: 8080
    targetPort: 8080

